# Generated by Django 4.0 on 2022-09-15 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='comments',
        ),
    ]
